language: Haskell

ghc: "7.10"

addons:
  apt:
    packages:
      - "haskell-platform"
      - "cabal-install"
	  
install: 
  - "nproc --all"
  - "sudo chmod +rwxrwxrwx $PWD -R"
  - "mkdir .status"
  - "sudo ./setup/install-dependencies"
  - "sudo ./setup/install-npm"
  - "sudo ./setup/install-pyjs"
  - "sudo ./setup/install-jsil"
  - "sudo ./setup/install-dragome"
  - "sudo ./setup/install-ghcjs"
  - "sudo ./setup/install-emscripten"
  - "sudo ./env-setup" 
  
script:
  - "sudo ./tests.py"

notifications:
  email: false
  
os: linux
dist: trusty
sudo: required
