#!/bin/bash

SCRIPTPATH=$(dirname "$(readlink -f "$0")")
BUILDDIR=$(dirname "$1")

# $1 is input file
# $2 is output file

FILENAME=$(basename "$1" .scm)

# Load emscripten onto the path
. ${SCRIPTPATH}/../emsdk_portable/emsdk_env.sh > /dev/null

cd $BUILDDIR

csc "$FILENAME.scm" -optimize-level 3 \
    -cc emcc -C -O3 -c
mv "$FILENAME.o" "$FILENAME.bc"

ls

emcc "$FILENAME.bc" -O3 -o "$FILENAME.js"

