#!/bin/bash

if [ ! -f ".status/JSIL" ]; then
	# Install msbuild
	git clone https://github.com/microsoft/msbuild.git --branch xplat --depth 1
	./msbuild/cibuild.sh

	# Install JSIL
	git clone https://github.com/sq/JSIL.git --depth 1
	cd JSIL
	git submodule update --init --recursive
	msbuild JSIL.sln
	cd ../
fi